// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK5QVUGYhESsvzGqfXGJ-cqkQmyPxubdo',
    appId: '1:222727693667:web:276e3bac8c22734bb11f56',
    messagingSenderId: '222727693667',
    projectId: 'gameup-375b0',
    authDomain: 'gameup-375b0.firebaseapp.com',
    storageBucket: 'gameup-375b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tnsUMBTlyE27XwqcFlc9Tq0LoukOlnc',
    appId: '1:222727693667:android:30ee98928fc727ccb11f56',
    messagingSenderId: '222727693667',
    projectId: 'gameup-375b0',
    storageBucket: 'gameup-375b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHgBYijHLNpY4IQ5hXG0JWJ7Q7oGTKFCU',
    appId: '1:222727693667:ios:76207ee142925ed5b11f56',
    messagingSenderId: '222727693667',
    projectId: 'gameup-375b0',
    storageBucket: 'gameup-375b0.firebasestorage.app',
    androidClientId: '222727693667-3vgf2gojar0k56lav96cjlt4i45iro0p.apps.googleusercontent.com',
    iosClientId: '222727693667-k76eq5un1ut28ngnlbo18i19ehbf35h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsMeetup',
  );

}